# Generated by Django 6.0.2 on 2026-02-14 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_financialprofile_email_otp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialprofile',
            name='is_phone_verified',
        ),
        migrations.RemoveField(
            model_name='financialprofile',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='financialprofile',
            name='phone_otp',
        ),
    ]
