# Generated by Django 6.0.2 on 2026-05-19 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_financialprofile_is_phone_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialprofile',
            name='is_email_verified',
            field=models.BooleanField(default=True),
        ),
    ]
